"""TracingInsights public F1 data (github.com/TracingInsights) — the
telemetry fallback and the whole-session source.

WHAT IT IS. One Apache-2.0 repository per season (TracingInsights/2026,
/2025, …), regenerated by GitHub Actions about 30 minutes after every
session from FastF1 (itself built on F1's live-timing feed), with Race lap
times cross-checked against Jolpica and mini-sectors taken from OpenF1. So
it is the same underlying timing data OpenF1 serves, republished as static
files: keyless, on GitHub's raw CDN, and not subject to OpenF1's free-tier
rate limit (3 req/s, 30 req/min). Attribution is appreciated, not required.

LAYOUT (verified against the 2026 repository tree, 2026-09-29):

    {Event name}/{Session name}/drivers.json            roster, team colours
    {Event name}/{Session name}/session_laptimes.json   every driver's laps
    {Event name}/{Session name}/corners.json            corner distances
    {Event name}/{Session name}/{DRV}/laptimes.json     one driver's laps
    {Event name}/{Session name}/{DRV}/{lap}_tel.json    one lap's telemetry

Files are columnar ({"time": [...], "lap": [...], ...}) and write missing
values as the string "None". Brake is a 0/1 flag and DRS is collapsed to
0/1; both are mapped onto OpenF1's conventions so the frontend sees one
shape whichever source answered.

Events are named, not keyed, so OpenF1's circuit_short_name is mapped to
the event folder below. Only names present in a repository tree were used;
an unmapped circuit is reported as unavailable, never guessed at.
"""

from __future__ import annotations

import math
from collections import OrderedDict
from typing import Any
from urllib.parse import quote

import httpx

from app.config import settings
from app.schemas.telemetry import (
    SessionLap,
    SessionOverview,
    SessionOverviewDriver,
    TelemetryCorner,
    TelemetryDriver,
    TelemetryLap,
    TelemetryLapTrace,
    TelemetrySample,
)
from app.services.telemetry_service import TelemetryUnavailable, TelemetryUpstreamError

_TIMEOUT = httpx.Timeout(15.0)


class SessionNotPublished(TelemetryUnavailable):
    """TracingInsights has nothing for the whole session (unmapped event, or
    its files aren't there). Distinct from a driver or lap that is missing
    *within* a published session: that absence is authoritative — it's the
    same timing data OpenF1 serves — whereas this one only says the backup
    doesn't cover the session. The pipeline treats the two differently."""

# OpenF1 circuit_short_name -> TracingInsights event folder. From the 2026
# repository tree; circuits not yet raced in 2026 use the same FastF1 event
# names the 2025 repository uses.
_EVENT_BY_CIRCUIT: dict[str, str] = {
    "Melbourne": "Australian Grand Prix",
    "Shanghai": "Chinese Grand Prix",
    "Suzuka": "Japanese Grand Prix",
    "Sakhir": "Bahrain Grand Prix",
    "Jeddah": "Saudi Arabian Grand Prix",
    "Miami": "Miami Grand Prix",
    "Imola": "Emilia Romagna Grand Prix",
    "Monte Carlo": "Monaco Grand Prix",
    "Montreal": "Canadian Grand Prix",
    "Catalunya": "Spanish Grand Prix",
    "Spielberg": "Austrian Grand Prix",
    "Silverstone": "British Grand Prix",
    "Spa-Francorchamps": "Belgian Grand Prix",
    "Hungaroring": "Hungarian Grand Prix",
    "Zandvoort": "Dutch Grand Prix",
    "Monza": "Italian Grand Prix",
    "Madring": "Spanish Grand Prix",
    "Baku": "Azerbaijan Grand Prix",
    "Singapore": "Singapore Grand Prix",
    "Austin": "United States Grand Prix",
    "Mexico City": "Mexico City Grand Prix",
    "Interlagos": "São Paulo Grand Prix",
    "Las Vegas": "Las Vegas Grand Prix",
    "Lusail": "Qatar Grand Prix",
    "Yas Marina Circuit": "Abu Dhabi Grand Prix",
}
# 2026 gave Madrid the Spanish Grand Prix name; Barcelona's round was
# renamed (the folder in the 2026 repository is "Barcelona Grand Prix").
_EVENT_OVERRIDES: dict[tuple[int, str], str] = {(2026, "Catalunya"): "Barcelona Grand Prix"}

# 2026 cars have no DRS (Overtake Mode replaced it). TracingInsights still
# writes a 0 for the channel; report it as absent, as OpenF1 does.
_FIRST_SEASON_WITHOUT_DRS = 2026
_DRS_OPEN_CODE = 12  # an OpenF1 "open" code, so the frontend reads it as open

# Static files for finished sessions: cache a bounded number of payloads
# per warm instance (a lap's telemetry is ~110 KB, a session's laps ~400 KB).
_CACHE_SIZE = 48
_json_cache: OrderedDict[str, Any] = OrderedDict()


def event_folder(year: int, circuit_short_name: str) -> str | None:
    return _EVENT_OVERRIDES.get((year, circuit_short_name)) or _EVENT_BY_CIRCUIT.get(circuit_short_name)


def _na(value: Any) -> Any:
    """TracingInsights writes missing values as the string "None"."""
    if value is None or value == "None":
        return None
    if isinstance(value, float) and math.isnan(value):
        return None
    return value


def _num(value: Any) -> float | None:
    value = _na(value)
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _column(payload: dict[str, Any], key: str, length: int) -> list[Any]:
    column = payload.get(key)
    if isinstance(column, list) and len(column) == length:
        return column
    return [None] * length


def _segment(value: str) -> str:
    """One path segment of the raw URL. The session name comes straight
    from the query string, and quote() leaves "/" alone and can't make "."
    or ".." safe, so anything that could climb out of the event folder is
    refused rather than escaped."""
    if not value or value in (".", "..") or "/" in value or "\\" in value:
        raise SessionNotPublished(f"{value!r} isn't a TracingInsights session or file name.")
    return quote(value, safe="")


def _url(year: int, circuit_short_name: str, session_name: str, *path: str) -> str:
    event = event_folder(year, circuit_short_name)
    if event is None:
        raise SessionNotPublished(
            f"TracingInsights has no event mapping for circuit {circuit_short_name!r}."
        )
    parts = [event, session_name, *path]
    return f"{settings.tracinginsights_raw_base_url}/{year}/main/" + "/".join(_segment(p) for p in parts)


async def _get_json(client: httpx.AsyncClient, url: str) -> Any:
    cached = _json_cache.get(url)
    if cached is not None:
        _json_cache.move_to_end(url)
        return cached
    try:
        response = await client.get(url)
    except httpx.HTTPError as exc:
        raise TelemetryUpstreamError(f"TracingInsights request failed: {url}") from exc
    if response.status_code == 404:
        raise TelemetryUnavailable(f"TracingInsights hasn't published {url.rsplit('/', 1)[-1]} for this session.")
    try:
        response.raise_for_status()
        payload = response.json()
    except (httpx.HTTPStatusError, ValueError) as exc:
        raise TelemetryUpstreamError(f"TracingInsights returned an unusable response for {url}") from exc
    _json_cache[url] = payload
    while len(_json_cache) > _CACHE_SIZE:
        _json_cache.popitem(last=False)
    return payload


def _parse_drivers(payload: Any) -> list[tuple[str, TelemetryDriver]]:
    rows = payload.get("drivers") if isinstance(payload, dict) else None
    out: list[tuple[str, TelemetryDriver]] = []
    for row in rows or []:
        try:
            code = str(row["driver"])
            first, last = str(_na(row.get("fn")) or ""), str(_na(row.get("ln")) or "")
            out.append(
                (
                    code,
                    TelemetryDriver(
                        driver_number=int(row["dn"]),
                        # Same "Given FAMILY" shape OpenF1 uses.
                        full_name=f"{first} {last.upper()}".strip(),
                        name_acronym=code,
                        team_name=str(_na(row.get("team")) or ""),
                        team_colour=_na(row.get("tc")),
                    ),
                )
            )
        except (KeyError, TypeError, ValueError):
            continue
    return sorted(out, key=lambda pair: pair[1].driver_number)


async def _roster(
    client: httpx.AsyncClient, year: int, circuit_short_name: str, session_name: str
) -> list[tuple[str, TelemetryDriver]]:
    try:
        payload = await _get_json(client, _url(year, circuit_short_name, session_name, "drivers.json"))
    except SessionNotPublished:
        raise
    except TelemetryUnavailable as exc:
        # No roster means no session, as far as this source is concerned.
        raise SessionNotPublished(str(exc)) from exc
    roster = _parse_drivers(payload)
    if not roster:
        raise SessionNotPublished("TracingInsights' driver list for this session is empty.")
    return roster


def _driver_code(roster: list[tuple[str, TelemetryDriver]], driver_number: int) -> tuple[str, TelemetryDriver]:
    for code, driver in roster:
        if driver.driver_number == driver_number:
            return code, driver
    raise TelemetryUnavailable(f"Driver {driver_number} isn't in TracingInsights' data for this session.")


async def get_drivers(year: int, circuit_short_name: str, session_name: str) -> list[TelemetryDriver]:
    async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
        return [driver for _, driver in await _roster(client, year, circuit_short_name, session_name)]


def _parse_laps(payload: Any) -> list[TelemetryLap]:
    if not isinstance(payload, dict):
        return []
    laps_col = payload.get("lap") or []
    times = _column(payload, "time", len(laps_col))
    laps: list[TelemetryLap] = []
    for lap, time in zip(laps_col, times):
        duration = _num(time)
        if duration is None or _na(lap) is None:
            continue
        laps.append(TelemetryLap(lap_number=int(lap), lap_duration=duration))
    return sorted(laps, key=lambda lap: lap.lap_number)


async def get_laps(
    driver_number: int, year: int, circuit_short_name: str, session_name: str
) -> list[TelemetryLap]:
    async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
        code, _ = _driver_code(await _roster(client, year, circuit_short_name, session_name), driver_number)
        payload = await _get_json(client, _url(year, circuit_short_name, session_name, code, "laptimes.json"))
    laps = _parse_laps(payload)
    if not laps:
        raise TelemetryUnavailable(f"No timed laps found for driver {driver_number} in this session.")
    return laps


def _parse_samples(payload: Any, year: int) -> list[TelemetrySample]:
    tel = payload.get("tel") if isinstance(payload, dict) else None
    if not isinstance(tel, dict):
        return []
    times = tel.get("time") or []
    n = len(times)
    speed, throttle, brake = (_column(tel, k, n) for k in ("speed", "throttle", "brake"))
    rpm, gear, drs = (_column(tel, k, n) for k in ("rpm", "gear", "drs"))
    distance, xs, ys = (_column(tel, k, n) for k in ("distance", "x", "y"))
    no_drs = year >= _FIRST_SEASON_WITHOUT_DRS

    samples: list[TelemetrySample] = []
    for i in range(n):
        t, v = _num(times[i]), _num(speed[i])
        if t is None or v is None:
            continue
        drs_flag = _num(drs[i])
        samples.append(
            TelemetrySample(
                t=t,
                speed=v,
                throttle=_num(throttle[i]) or 0.0,
                # 0/1 flag -> OpenF1's 0/100 scale.
                brake=100.0 if (_num(brake[i]) or 0.0) > 0 else 0.0,
                rpm=_num(rpm[i]) or 0.0,
                gear=int(_num(gear[i]) or 0),
                drs=None if no_drs or drs_flag is None else (_DRS_OPEN_CODE if drs_flag > 0 else 0),
                distance=_num(distance[i]),
                x=_num(xs[i]),
                y=_num(ys[i]),
            )
        )
    samples.sort(key=lambda s: s.t)
    return samples


async def get_lap_trace(
    driver_number: int, lap_number: int, year: int, circuit_short_name: str, session_name: str
) -> TelemetryLapTrace:
    async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
        code, driver = _driver_code(await _roster(client, year, circuit_short_name, session_name), driver_number)
        laps = _parse_laps(
            await _get_json(client, _url(year, circuit_short_name, session_name, code, "laptimes.json"))
        )
        lap = next((l for l in laps if l.lap_number == lap_number), None)
        if lap is None:
            raise TelemetryUnavailable(f"Lap {lap_number} for driver {driver_number} isn't a timed lap.")
        payload = await _get_json(
            client, _url(year, circuit_short_name, session_name, code, f"{lap_number}_tel.json")
        )

    samples = _parse_samples(payload, year)
    if not samples:
        raise TelemetryUnavailable(
            f"TracingInsights has no telemetry samples for driver {driver_number}'s lap {lap_number}."
        )
    return TelemetryLapTrace(
        year=year,
        session_name=session_name,
        circuit_short_name=circuit_short_name,
        driver=driver,
        lap_number=lap_number,
        lap_duration=lap.lap_duration,
        samples=samples,
        source="tracinginsights",
    )


async def get_corners(year: int, circuit_short_name: str, session_name: str) -> list[TelemetryCorner]:
    async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
        payload = await _get_json(client, _url(year, circuit_short_name, session_name, "corners.json"))
    if not isinstance(payload, dict):
        return []
    numbers = payload.get("CornerNumber") or []
    distances = _column(payload, "Distance", len(numbers))
    xs = _column(payload, "X", len(numbers))
    ys = _column(payload, "Y", len(numbers))
    corners = [
        TelemetryCorner(number=int(n), distance=d, x=_num(x), y=_num(y))
        for n, d, x, y in ((_na(n), _num(d), x, y) for n, d, x, y in zip(numbers, distances, xs, ys))
        if n is not None and d is not None
    ]
    return sorted(corners, key=lambda c: c.distance)


def _truthy(value: Any) -> bool:
    return _na(value) is not None


async def get_session_overview(year: int, circuit_short_name: str, session_name: str) -> SessionOverview:
    async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
        roster = await _roster(client, year, circuit_short_name, session_name)
        payload = await _get_json(client, _url(year, circuit_short_name, session_name, "session_laptimes.json"))
    if not isinstance(payload, dict) or not payload.get("drv"):
        raise SessionNotPublished("TracingInsights has no session lap data for this session.")

    n = len(payload["drv"])
    col = {k: _column(payload, k, n) for k in ("lap", "time", "compound", "stint", "pos", "pin", "pout", "status")}
    laps: list[SessionLap] = []
    for i in range(n):
        lap = _num(col["lap"][i])
        if lap is None:
            continue
        stint, pos = _num(col["stint"][i]), _num(col["pos"][i])
        laps.append(
            SessionLap(
                driver=str(payload["drv"][i]),
                lap=int(lap),
                time=_num(col["time"][i]),
                compound=_na(col["compound"][i]),
                stint=int(stint) if stint is not None else None,
                position=int(pos) if pos is not None else None,
                pit_in=_truthy(col["pin"][i]),
                pit_out=_truthy(col["pout"][i]),
                status=_na(col["status"][i]),
            )
        )

    return SessionOverview(
        year=year,
        session_name=session_name,
        circuit_short_name=circuit_short_name,
        event_name=event_folder(year, circuit_short_name) or circuit_short_name,
        source="tracinginsights",
        drivers=[
            SessionOverviewDriver(
                code=code,
                driver_number=d.driver_number,
                full_name=d.full_name,
                team_name=d.team_name,
                team_colour=d.team_colour,
            )
            for code, d in roster
        ],
        laps=laps,
    )
